name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version: [ '8.0' ]
        include:
          - { operating-system: 'ubuntu-latest', php-version: '8.0', }
          - { operating-system: 'ubuntu-latest', php-version: '8.1', }

    name: PHP ${{ matrix.php-version }} (${{ matrix.operating-system }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=512M, xdebug.mode=off
          tools: composer:v2.1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}-
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-progress
      

      - name: Run unit tests
        shell: bash
        run: |
          make test

      - name: Run PHP CS fixer
        shell: bash
        run: |
          make cs-fix
